### ISSUE TITLE
主题无法配置

### ISSUE THREAD

**Issue by li1753846989** [LIlGG/halo-comment-sakura#14]
1. halo后台点击主题配置保存按钮,报500
2. 数据库为mysql 5.7
3. 查看数据字段发现不存在该自动
![image](https://user-images.githubusercontent.com/50787560/106230370-4d4d6b80-622a-11eb-97f8-c0e1c11aceba.png)

4. 疑似主题配置文件问题

**Comment by LIlGG** [comment]
可以提供后台报错日志吗？我想了解一下是哪个配置字段的错误

**Comment by li1753846989** [comment]
-- Logs begin at Mon 2020-12-28 11:50:15 CST, end at Fri 2021-01-29 13:33:31 CST. --
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128) ~[hibernate-core-5.4.27.Final.jar!/:5.4.27.Final]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1648) ~[hibernate-core-5.4.27.Final.jar!/:5.4.
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111) ~[hibern
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196) ~[spring-data-jp
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88) ~[spring-data-jpa-2.4.3.jar!/:2.4.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:155) ~[spring-data-jpa-2.4.3.jar!/:2.4.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:143) ~[spring-data-jpa-2.4.3.jar!/:2.4.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.4.
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152) ~[spring-d
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131) ~[spring-dat
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-d
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.3.jar!/:5.3.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar!/:5.3.3]
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spr
Jan 29 13:33:31 iZ13zr5pyzzm9pZ java[1772]: ... 135 common frames omitted
~
